### ISSUE TITLE
翻了很久的代码，只发现feign调用，没发现dubbo的服务调用

### ISSUE THREAD

**Issue by liunewshine** [yinjihuan/kitty-cloud#1]
请问下哪里有使用dubbo呢？我想参考下

**Comment by yinjihuan** [comment]
比如com.cxytiandi.kittycloud.article.provider.service.ArticleRemoteServiceImpl类就是暴露了dubbo服务，加了dubbo的@Service注解。

**Comment by liunewshine** [comment]
哪里有服务调用呢，dubbo的服务调用应该有@reference才对？

**Comment by yinjihuan** [comment]
你看下com.cxytiandi.kittycloud.article.biz.manager.impl.UserManagerImpl里的代码就知道了

**Comment by liunewshine** [comment]
多謝，看到了。
顺便问下项目中为啥集成dubbo和feign两种服务调用框架呢？是不是正常项目一个就能满足需求？

**Comment by yinjihuan** [comment]
是的，无论用哪种都可以。比如某些对性能要求很高的场景就可以用rpc
